### ISSUE TITLE
Conversoes de medidas

### ISSUE THREAD

**Issue by KC2016** [TeoCalvo/teoSQL-V2#1]
Nas tarefas 2 e 4 para casa da aula 1, eu assumi a densidade da água nas conversões de grama para litro, que certamente não é a mesma de produtos, na verdade.
Era essa a sua ideia?

Ex2: Quantos produtos tem mais de 5 litros?
Ex4: Quantos produtos de 'beleza_saude' com menos de 1 litro?
Os produtos em grama (product_weight_g)

**Comment by TeoCalvo** [comment]
Acredito que sanamos essa dúvida durante a live, certo?
